behance/BeFF

- ux/scrollfloat.js
This reverts commit 339c2b95972caeddc40043fbaa054ce3a3d26c6f.
> Revert "Scrollfloat: dont unblock throttling on promise rejection"

- Component/CloudUploader.js
- bower.json
- test/lib/main.js
- test/mocks/fineuploader.js
- test/specs/Component/CloudUploader.js
> RFC: CloudUploader: initial commit with tests to follow

- Component/CloudUploader.js
- test/specs/Component/CloudUploader.js
https://github.com/behance/issues/issues/3567
Sending the lightroom image blobs through cloudthrough
Poet code will be something like
```js
export function uploadBlobs(config, blobs, options) {
return CloudUploader.promiseBlobs(getOptions(config, options), blobs);
}
export function upload(config, options) {
return CloudUploader.promise(getOptions(config, options));
}
```
> Component/CloudUploader: support uploading an array of blobs

- test/fixtures/ux/CharCounter.html
- test/specs/ux/CharCounter.js
- ux/CharCounter.js
This would make one sick ractive component.
> Character counter for counting characters

- test/specs/util/validate.js
- util/validate.js
I found some cases that was missed by both the js regexp as well as the php regexp. @jimdelois is looking at updating the php side.
> Validation: email test missed some cases

- util/validate.js
@joesepi @jrefano  cc: @be-dmitry 
adobe-community/issues#5237
> Validate: change message for getUsername

- Component/StickyPenScroller.js
Used throughout Portfolio and now used on the Network's poet-powered project editor
Tests will be backfilled (https://github.com/adobe-community/issues/issues/7506).
> StickyPenScroller: promote to beff

- test/specs/util/validate.js
- util/validate.js
Add requireTrimmed into core validation rules
> add requireTrimmed

- test/specs/util/remoteLogger.js
- util/remoteLogger.js
- util/window.js
https://github.com/adobe-community/issues/issues/8018
Most of the library is intact, some minor changes made are commented.
> RemoteLogger: bringing over from the network

- test/specs/util/validate.js
- util/validate.js
> Validate: update email regex to not allow invalid email addresses

- Component/LazyLoadImg.js
- bower.json
- package.json
- test/lib/main.js
- test/specs/Component/LazyLoadImg.js
https://github.com/adobe-community/issues/issues/7303
https://github.com/adobe-community/issues/issues/9362
Pro2-ui implementation: https://github.com/behance/pro2-ui/pull/1708/files
> LazyLoadImg: LazyLoad images using Intersection Observer

- test/specs/util/validate.js
- util/validate.js
@mikesherov @Attamusc @weikinhuang
> Validate: Add URL inclusion

- View/Dialog/Popup.js
- test/specs/View/Dialog/Popup.js
Fixes various issues we're seen with popup's not stacking correctly when multiple versions
of BeFF exist on a page.
> Popup: Use existing popups to calculate stacking

- Component/CloudUploader/facades/promises.js
- test/specs/Component/CloudUploader.js
Refs adobe-community/issues#12484
> CloudUploader: propagate the original file name

- test/specs/util/uploadValidator.js
- util/uploadValidator.js
Addresses: https://github.com/adobe-community/issues/issues/14395
> Upload Validator: update copy for CMYK Warning Message.

- test/specs/util/uploadValidator.js
- util/uploadValidator.js
Addresses: https://github.com/adobe-community/issues/issues/14395
> CMYK Warning: Open link from warning in new tab

- test/specs/util/uploadValidator.js
- util/uploadValidator.js
Addresses: https://github.com/adobe-community/issues/issues/14395
> Upload Validator: new CMYK validator that just returns true/false, representing whether validated file is/is not a CMYK image

- View/Dialog.js
Requires: https://github.com/behance/be.net/pull/13740
Refers to https://github.com/adobe-community/issues/issues/14535
> Updating syntax for webpack 2.2.1

- package.json
- test/specs/util/csrfCookie.js
- util/csrfCookie.js
Fixes: adobe-community/issues#15331
> CSRF: Generate cookie value using uuid lib

- test/specs/util/validate.js
- util/validate.js
Allow length to accept min (`length[3,]`), max (`length[,3]`), and range (`length[3,5]`)
> Fix regex length issue

- Component/CloudUploader.js
- package.json
- test/specs/Component/CloudUploader.js
- webpack.config.js
Ref https://github.com/behance/fine-uploader/pull/9
> Use new fine-uploader without alias

- package-lock.json
- ux/scrollfloat.js
- ux/scrollpoint.js
Refs: https://github.com/adobe-community/issues/issues/20006
> Scrollpoint/Scrollfloat: Don't save $(window) and $(document) in a variable outside of function call. Makes these beff imports ssr-able.

- package-lock.json
- package.json
- test/specs/util/validate.js
- util/validate.js
Refs: adobe-community/issues/issues/21403
> Validate: ContainsEmail and stronger ContainsUrl

- test/specs/util/validate.js
- util/validate.js
- was matching strings like, 'In other words...I....LOVE IT!'
Refs: adobe-community/issues/issues/22205
> Validation: fix to url regex

- README.md
> Readme should reference BeFF instead of Poet

- Component/CloudUploader.js
- test/mocks/fineuploader.js
- test/specs/Component/CloudUploader.js
Fixes
with file types other than images
> Clouduploader: check file type before scaling the file

- Component/CloudUploader.js
- test/mocks/fineuploader.js
- test/specs/Component/CloudUploader.js
ref: adobe-community/issues/issues/25526
Should not attempt to orientation correct moving gif images. It removes the animation when it does.
> Clouduploader: do not orientation correct gif files
